---
version: "3.3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    links:
      - dns
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - SERVERURL=auto #optional
      - SERVERPORT=51820 #optional
      - PEERS=10 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=1.1.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ~/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  dns:
    image: qmcgaw/dns
    container_name: dns
    environment:
      - VERBOSITY=1
      - VERBOSITY_DETAILS=0
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
      - BLOCK_IPS=
      - BLOCK_HOSTNAMES=youtube.com
      - UNBLOCK=
      - PROVIDERS=cloudflare,quad9
      - UPDATE_PERIOD=24h
    ports:
      - 53:53/udp
    network_mode: bridge
    volumes:
      - ./conf/unbound.conf:/unbound/unbound.conf
    restart: always